name: Database Deployment

on:
  workflow_dispatch:
    inputs:
       environment:
        description: 'Environment'
        type: environment
  push:
    branches:
      - master
  
env:
      SQL_SERVER_NAME: ${syn01-prod-ondemand.sql.azuresynapse.net}
      CONNECTION_STRING: ${Server=tcp:syn01-dev-ondemand.sql.azuresynapse.net,1433;Database=synprod01;User ID=sqladminuser;Password=sql!12345;Encrypt=true;TrustServerCertificate=false;Connection Timeout=100;}
      WORKING_DIRECTORY: C:\Users\salendra.d\source\repos\synapsecicd_07072023
      CLIENT_ID: ${d7b6a13c-fa42-4ddb-ad02-dc94970e25a2}
      TENANT_ID: ${865cc515-a530-4538-8ef8-072b7b2be759}
      RESOURCE_GROUP: ${Team_Practise}

jobs:
  build :
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to Workspace
        run: |
          cd synapsecicd_07072023
          pwd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      

      - name: Build DACPAC
        run: msbuild 'C:\Users\salendra.d\source\repos\synapsecicd_07072023\synapsecicd_07072023.sln' /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name:  SQLDB
          path: ${{ github.workspace }}/DBADirectory/bin/debug/ 

          
  deploy: 
    needs: build
    environment: DEV
    runs-on: windows-latest

    steps:
      - name: login to az
        shell: bash
        run: |
          az login --service-principal -u $CLIENT_ID --tenant $TENANT_ID
               
      - name: download artifact containing dacpac
        uses: actions/download-artifact@v3.0.2
        with:
          name: SQLDB

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.1
        with:
          connection-string: '${{ secrets.CONNECTION_STRING }}'
          path: './synapsecicd_07072023.dacpac'
          action: publish
          arguments: '/p:DropObjectsNotInSource=true'



